# Clash配置文件示例
# 基于您的代理服务器配置

mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
external-controller: :9090

proxies:
  # 香港IPLC代理
  - name: HongKong-IPLC-HK-1
    type: trojan
    server: iplc-hk-1.trojanwheel.com
    port: 465
    password: GUGm7DHtpSx7SuPyUD
    udp: true
    sni: iplc-hk-1.trojanwheel.com

  - name: HongKong-IPLC-HK-2
    type: trojan
    server: iplc-hk-2.trojanwheel.com
    port: 465
    password: GUGm7DHtpSx7SuPyUD
    udp: true
    sni: iplc-hk-2.trojanwheel.com

  # 日本代理
  - name: Japan-TY-1
    type: trojan
    server: ty-1.rise-fuji.com
    port: 443
    password: GUGm7DHtpSx7SuPyUD
    udp: true
    sni: ty-1.rise-fuji.com

  # 美国代理
  - name: UnitedStates-US-1
    type: trojan
    server: us-1.regentgrandvalley.com
    port: 443
    password: GUGm7DHtpSx7SuPyUD
    udp: true
    sni: us-1.regentgrandvalley.com

  # 新加坡代理
  - name: Singapore-SG-1
    type: trojan
    server: sg-1.victoriamitrepeak.com
    port: 443
    password: GUGm7DHtpSx7SuPyUD
    udp: true
    sni: sg-1.victoriamitrepeak.com

  # 澳大利亚代理
  - name: Australia-AU-1
    type: trojan
    server: au-1.australiastudio.com
    port: 443
    password: GUGm7DHtpSx7SuPyUD
    udp: true
    sni: au-1.australiastudio.com

proxy-groups:
  # 代理选择组
  - name: Proxy
    type: select
    proxies:
      - Auto
      - HongKong-IPLC-HK-1
      - HongKong-IPLC-HK-2
      - Japan-TY-1
      - UnitedStates-US-1
      - Singapore-SG-1
      - Australia-AU-1
      - DIRECT

  # 自动选择组
  - name: Auto
    type: url-test
    proxies:
      - HongKong-IPLC-HK-1
      - HongKong-IPLC-HK-2
      - Japan-TY-1
      - UnitedStates-US-1
      - Singapore-SG-1
      - Australia-AU-1
    url: https://www.google.com/generate_204
    interval: 300

rules:
  # 直连规则
  - DOMAIN-SUFFIX,cn,DIRECT
  - DOMAIN-SUFFIX,baidu.com,DIRECT
  - DOMAIN-SUFFIX,qq.com,DIRECT
  - DOMAIN-SUFFIX,taobao.com,DIRECT
  - DOMAIN-SUFFIX,jd.com,DIRECT
  - DOMAIN-SUFFIX,163.com,DIRECT
  - DOMAIN-SUFFIX,126.com,DIRECT
  - DOMAIN-SUFFIX,sohu.com,DIRECT
  - DOMAIN-SUFFIX,sina.com.cn,DIRECT
  - DOMAIN-SUFFIX,weibo.com,DIRECT
  - DOMAIN-SUFFIX,zhihu.com,DIRECT
  - DOMAIN-SUFFIX,bilibili.com,DIRECT
  
  # 代理规则
  - DOMAIN-SUFFIX,google.com,Proxy
  - DOMAIN-SUFFIX,youtube.com,Proxy
  - DOMAIN-SUFFIX,facebook.com,Proxy
  - DOMAIN-SUFFIX,twitter.com,Proxy
  - DOMAIN-SUFFIX,instagram.com,Proxy
  - DOMAIN-SUFFIX,github.com,Proxy
  - DOMAIN-SUFFIX,stackoverflow.com,Proxy
  - DOMAIN-SUFFIX,reddit.com,Proxy
  - DOMAIN-SUFFIX,wikipedia.org,Proxy
  
  # 默认规则
  - MATCH,Proxy
