tunnel: shenyiqing-tunnel
credentials-file: /Users/gaojie/.cloudflared/shenyiqing-tunnel.json

ingress:
  - hostname: shenyiqing.xin
    service: http://localhost:8000
    originRequest:
      httpHostHeader: shenyiqing.xin
      # 增加超时时间解决AI生成问题
      connectTimeout: 60s
      tlsTimeout: 30s
      keepAliveTimeout: 900s  # 15分钟
      tcpKeepAlive: 60s
      keepAliveConnections: 20
      bufferSize: 131072
  - service: http_status:404

# SSL配置
originRequest:
  # 启用HTTPS
  tlsTimeout: 30s
  # 禁用证书验证（用于开发环境）
  noTLSVerify: false

# 日志配置
logfile: /Users/gaojie/.cloudflared/cloudflared.log
loglevel: info
