tunnel: shenyiqing-tunnel
ingress:
  - hostname: shenyiqing.xin
    service: http://localhost:8000
    originRequest:
      # 设置更长的超时时间 - 解决AI生成超时问题
      connectTimeout: 60s
      tlsTimeout: 30s
      tcpKeepAlive: 60s
      keepAliveConnections: 20
      keepAliveTimeout: 900s  # 15分钟超时
      # 禁用压缩以避免大响应的问题
      disableChunkedEncoding: false
      # 设置更大的缓冲区
      bufferSize: 131072
      # 增加HTTP超时
      httpHostHeader: shenyiqing.xin
      # 允许长连接
      noTLSVerify: false
  - service: http_status:404
