# Generated by Django 4.2.7 on 2025-09-06 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("device_id", models.CharField(max_length=100, unique=True)),
                ("device_type", models.CharField(max_length=50)),
                ("device_name", models.CharField(blank=True, max_length=100)),
                ("platform", models.CharField(max_length=50)),
                ("app_version", models.CharField(blank=True, max_length=20)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="login_sessions", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "登录会话",
                "verbose_name_plural": "登录会话",
                "db_table": "unified_login_sessions",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="DataSyncLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("device_id", models.CharField(max_length=100)),
                ("data_type", models.CharField(max_length=50)),
                ("sync_id", models.CharField(max_length=100, unique=True)),
                ("data_size", models.IntegerField(default=0)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[("pending", "待同步"), ("success", "同步成功"), ("failed", "同步失败")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sync_logs", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "数据同步日志",
                "verbose_name_plural": "数据同步日志",
                "db_table": "data_sync_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
