# Generated by Django 4.2.23 on 2025-08-23 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0065_shipbao_want_features'),
    ]

    operations = [
    ]
