# Generated by Django 4.2.23 on 2025-08-23 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0066_auto_20250823_1548'),
        ('tools', '0066_shipbao_enhancements'),
    ]

    operations = [
    ]
