# Generated by Django 4.2.23 on 2025-08-23 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0067_merge_20250823_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipBaoInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待响应'), ('responded', '已响应'), ('ignored', '已忽略'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('initial_message', models.TextField(blank=True, verbose_name='初始消息')),
                ('priority_score', models.IntegerField(default=0, verbose_name='优先级分数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='响应时间')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipbao_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='买家')),
                ('chat_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.chatroom', verbose_name='聊天室')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='tools.shipbaoitem', verbose_name='商品')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='卖家')),
            ],
            options={
                'verbose_name': '商品咨询',
                'verbose_name_plural': '商品咨询',
                'ordering': ['-priority_score', 'created_at'],
                'indexes': [
                    models.Index(fields=['item', 'status'], name='tools_shipb_item_id_017fee_idx'),
                    models.Index(fields=['seller', 'status', 'created_at'], name='tools_shipb_seller__4d172c_idx'),
                    models.Index(fields=['buyer', 'status'], name='tools_shipb_buyer_i_9b5673_idx'),
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name='shipbaoinquiry',
            unique_together={('item', 'buyer')},
        ),
    ]
