/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AIWritingManagement: typeof import('./src/components/life-tools/AIWritingManagement.vue')['default']
    AnalysisManagement: typeof import('./src/components/geek-tools/AnalysisManagement.vue')['default']
    APISettings: typeof import('./src/components/settings/APISettings.vue')['default']
    Base64Management: typeof import('./src/components/geek-tools/Base64Management.vue')['default']
    BasicSettings: typeof import('./src/components/settings/BasicSettings.vue')['default']
    BuddyEventsManagement: typeof import('./src/components/social/BuddyEventsManagement.vue')['default']
    ChatManagement: typeof import('./src/components/social/ChatManagement.vue')['default']
    CheckinManagement: typeof import('./src/components/life-tools/CheckinManagement.vue')['default']
    CrawlerManagement: typeof import('./src/components/geek-tools/CrawlerManagement.vue')['default']
    DiaryManagement: typeof import('./src/components/life-tools/DiaryManagement.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FeatureSettings: typeof import('./src/components/settings/FeatureSettings.vue')['default']
    FoodManagement: typeof import('./src/components/life-tools/FoodManagement.vue')['default']
    FormatterManagement: typeof import('./src/components/geek-tools/FormatterManagement.vue')['default']
    FortuneManagement: typeof import('./src/components/social/FortuneManagement.vue')['default']
    HashManagement: typeof import('./src/components/geek-tools/HashManagement.vue')['default']
    HeartLinkManagement: typeof import('./src/components/social/HeartLinkManagement.vue')['default']
    MeditationManagement: typeof import('./src/components/life-tools/MeditationManagement.vue')['default']
    NotificationSettings: typeof import('./src/components/settings/NotificationSettings.vue')['default']
    PDFManagement: typeof import('./src/components/geek-tools/PDFManagement.vue')['default']
    PWAManagement: typeof import('./src/components/share/PWAManagement.vue')['default']
    QRCodeManagement: typeof import('./src/components/geek-tools/QRCodeManagement.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecuritySettings: typeof import('./src/components/settings/SecuritySettings.vue')['default']
    ShareLinksManagement: typeof import('./src/components/share/ShareLinksManagement.vue')['default']
    ShareRecordsManagement: typeof import('./src/components/share/ShareRecordsManagement.vue')['default']
    ShareWidgetsManagement: typeof import('./src/components/share/ShareWidgetsManagement.vue')['default']
    StoryManagement: typeof import('./src/components/social/StoryManagement.vue')['default']
    TarotManagement: typeof import('./src/components/social/TarotManagement.vue')['default']
    TestcaseManagement: typeof import('./src/components/geek-tools/TestcaseManagement.vue')['default']
    TravelManagement: typeof import('./src/components/social/TravelManagement.vue')['default']
  }
}
