name: Deploy to Aliyun Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        script: |
          cd ~/QAToolBox || cd /home/qatoolbox/QAToolBox || exit 1
          git pull origin main
          chmod +x quick-fix-deploy.sh
          ./quick-fix-deploy.sh
          echo "部署完成！"

